#!/bin/bash
cd lol-cpp
make
cd ..
stack exec ghci -- lol-cpp/lib/*.so $@

# change history so that :r is the "last" ghci command
# without this, :q is always the most recent command in the history
SED=$(which gsed || which sed)
[ -z ${SED} ] || ${SED} -i "1s/.*/:r/" "${HOME}/.ghc/ghci_history"

