
resolver: lts-8.2

packages:
#- fhe-compiler
- lol
- lol-apps
- lol-benches
- lol-cpp
- lol-repa
- lol-tests
#- rlwe-challenges

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- non-negative-0.1.1
- numeric-prelude-0.4.2
- tagged-transformer-0.8
- syntactic-3.6.3
- type-natural-0.7.1.3
- equational-reasoning-0.4.1.1
- monomorphic-0.0.3.3
#
- nist-beacon-0.2.0.0

# Extra package databases containing global packages
extra-package-dbs: []

# vim: nospell

